# Generated by Django 4.1.5 on 2023-01-28 17:10

import account.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='online_status', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('status', models.IntegerField(choices=[(0, 'online'), (1, 'offline')], default=1)),
            ],
            options={
                'verbose_name': 'online status',
                'verbose_name_plural': 'online status',
                'db_table': 'OnlineStatus',
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='no_avatar.png', upload_to=account.utils.get_avatar_path, verbose_name='avatar'),
        ),
    ]
