version: "3.8"

services:
    directchat:
        image: directchat:1.0.0
        container_name: directchat
        build: ./directchat
        restart: on-failure
        expose:
          - 8000
        volumes:
          - ./directchat/:/usr/src/directchat/
          - ./static/:/usr/src/static/
          - ./media/:/usr/src/media/
        depends_on:
          - postgres
          - redis
          - nginx

    postgres:
        image: postgres:14.5-alpine
        ports:
          - 5432:5432
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_DB: directchat
            POSTGRES_USER: directchat
            POSTGRES_PASSWORD: directchat
        volumes:
            - postgres-data:/var/lib/postgresql/data/

    redis:
        image: redis:6.2.7-alpine
        ports:
            - 6379:6379 
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - redis-data:/data

    nginx:
        build: ./nginx
        container_name: nginx
        restart: on-failure
        ports:
            - 80:80
        volumes:
            - ./static/:/static/
            - ./media/:/media/

volumes:
    postgres-data:
    redis-data: